### ISSUE TITLE
Maps section using older maps

### ISSUE THREAD

**Issue by onkoe** [osiux/phasmofinder#1]
Hello,
First of all, thanks for the nice little site! As a newer Phasmophobia player, I've found much of the information quite useful! However, the maps section seems to be a bit out of date. I have confirmation from u/Fantismal that the maps currently listed on your website are older than the ones [on Imgur](https://imgur.com/a/iEI0tJo). While you linked to the album, viewing from your website directly is quite a lot easier (and is listed directly on the wiki). Please consider updating the images manually or set the webpage to automatically use the Imgur links. 

Best, 
Onkoe

**Comment by osiux** [comment]
@onkoe thanks for reminding me of doing that! Just updated them, should be up as soon as deployment is complete!
